FROM alpine
RUN apk add curl && echo 'http://dl-cdn.alpinelinux.org/alpine/v3.6/main' >> /etc/apk/repositories && echo 'http://dl-cdn.alpinelinux.org/alpine/v3.6/community' >> /etc/apk/repositories
RUN apk update
RUN apk add mongodb && apk add mongodb-tools
RUN apk add openrc
RUN mkdir -p /data/db/
RUN chown root /data/db
RUN rc-update add mongodb default
CMD ["mongod", "--rest", "--httpinterface"]